# Generated by Django 3.2.4 on 2021-07-09 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewMoedel',
            new_name='NewModel',
        ),
    ]
